// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';

import * as DashboardApi from '../../api/DashboardApi';
import { createPromiseThunk } from '../../api/AsyncUtil';

//액션 타입
//?일간 많이 예약된 회의실 개수 조회
export const ONEDAY_ROOM_RESERVATION_LIST_GET = 'ONEDAY_ROOM_RESERVATION_LIST';
export const ONEDAY_ROOM_RESERVATION_LIST_GET_SUCCESS = 'ONEDAY_ROOM_RESERVATION_LIST_GET_SUCCESS';
export const ONEDAY_ROOM_RESERVATION_LIST_GET_ERROR = 'ONEDAY_ROOM_RESERVATION_LIST_GET_ERROR';

export const THREEDAY_ROOM_RESERVATION_LIST_GET = 'THREEDAY_ROOM_RESERVATION_LIST_GET';
export const THREEDAY_ROOM_RESERVATION_LIST_GET_SUCCESS = 'THREEDAY_ROOM_RESERVATION_LIST_GET_SUCCESS';
export const THREEDAY_ROOM_RESERVATION_LIST_GET_ERROR = 'THREEDAY_ROOM_RESERVATION_LIST_GET_ERROR';

export const SEVENDAY_ROOM_RESERVATION_LIST_GET = 'SEVENDAY_ROOM_RESERVATION_LIST_GET';
export const SEVENDAY_ROOM_RESERVATION_LIST_GET_SUCCESS = 'SEVENDAY_ROOM_RESERVATION_LIST_GET_SUCCESS';
export const SEVENDAY_ROOM_RESERVATION_LIST_GET_ERROR = 'SEVENDAY_ROOM_RESERVATION_LIST_GET_ERROR';

// //?일간 많이 예약하는 시간대 회의실 조회
// export const ONEDAY_ROOM_RESERVATION_TIME_LIST_GET = 'ONEDAY_ROOM_RESERVATION_TIME_LIST_GET';
// export const ONEDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS = 'ONEDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS';
// export const ONEDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR = 'ONEDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR';

// export const THREEDAY_ROOM_RESERVATION_TIME_LIST_GET = 'THREEDAY_ROOM_RESERVATION_TIME_LIST_GET';
// export const THREEDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS = 'THREEDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS';
// export const THREEDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR = 'THREEDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR';

// export const SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET = 'SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET';
// export const SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS = 'SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS';
// export const SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR = 'SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR';

// //?일간 많이 회의가 시작되는 시간대 회의실 조회
// export const ONEDAY_ROOM_MEET_TIME_LIST_GET = 'ONEDAY_ROOM_MEET_TIME_LIST_GET';
// export const ONEDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS = 'ONEDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS';
// export const ONEDAY_ROOM_MEET_TIME_LIST_GET_ERROR = 'ONEDAY_ROOM_MEET_TIME_LIST_GET_ERROR';

// export const THREEDAY_ROOM_MEET_TIME_LIST_GET = 'THREEDAY_ROOM_MEET_TIME_LIST_GET';
// export const THREEDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS = 'THREEDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS';
// export const THREEDAY_ROOM_MEET_TIME_LIST_GET_ERROR = 'THREEDAY_ROOM_MEET_TIME_LIST_GET_ERROR';

// export const SEVENDAY_ROOM_MEET_TIME_LIST_GET = 'SEVENDAY_ROOM_MEET_TIME_LIST_GET';
// export const SEVENDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS = 'SEVENDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS';
// export const SEVENDAY_ROOM_MEET_TIME_LIST_GET_ERROR = 'SEVENDAY_ROOM_MEET_TIME_LIST_GET_ERROR';

// //---------------------------------------------------------------------------------------------------
// //?일간 많이 예약된 회의실 개수 조회
// export const ONEDAY_ROOM_RESERVATION_LIST_GET = 'ONEDAY_ROOM_RESERVATION_LIST';
// export const ONEDAY_ROOM_RESERVATION_LIST_GET_SUCCESS = 'ONEDAY_ROOM_RESERVATION_LIST_GET_SUCCESS';
// export const ONEDAY_ROOM_RESERVATION_LIST_GET_ERROR = 'ONEDAY_ROOM_RESERVATION_LIST_GET_ERROR';

// export const THREEDAY_ROOM_RESERVATION_LIST_GET = 'THREEDAY_ROOM_RESERVATION_LIST_GET';
// export const THREEDAY_ROOM_RESERVATION_LIST_GET_SUCCESS = 'THREEDAY_ROOM_RESERVATION_LIST_GET_SUCCESS';
// export const THREEDAY_ROOM_RESERVATION_LIST_GET_ERROR = 'THREEDAY_ROOM_RESERVATION_LIST_GET_ERROR';

// export const SEVENDAY_ROOM_RESERVATION_LIST_GET = 'SEVENDAY_ROOM_RESERVATION_LIST_GET';
// export const SEVENDAY_ROOM_RESERVATION_LIST_GET_SUCCESS = 'SEVENDAY_ROOM_RESERVATION_LIST_GET_SUCCESS';
// export const SEVENDAY_ROOM_RESERVATION_LIST_GET_ERROR = 'SEVENDAY_ROOM_RESERVATION_LIST_GET_ERROR';

// //?일간 많이 예약하는 시간대 회의실 조회
// export const ONEDAY_ROOM_RESERVATION_TIME_LIST_GET = 'ONEDAY_ROOM_RESERVATION_TIME_LIST_GET';
// export const ONEDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS = 'ONEDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS';
// export const ONEDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR = 'ONEDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR';

// export const THREEDAY_ROOM_RESERVATION_TIME_LIST_GET = 'THREEDAY_ROOM_RESERVATION_TIME_LIST_GET';
// export const THREEDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS = 'THREEDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS';
// export const THREEDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR = 'THREEDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR';

// export const SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET = 'SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET';
// export const SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS = 'SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS';
// export const SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR = 'SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR';

// //?일간 많이 회의가 시작되는 시간대 회의실 조회
// export const ONEDAY_ROOM_MEET_TIME_LIST_GET = 'ONEDAY_ROOM_MEET_TIME_LIST_GET';
// export const ONEDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS = 'ONEDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS';
// export const ONEDAY_ROOM_MEET_TIME_LIST_GET_ERROR = 'ONEDAY_ROOM_MEET_TIME_LIST_GET_ERROR';

// export const THREEDAY_ROOM_MEET_TIME_LIST_GET = 'THREEDAY_ROOM_MEET_TIME_LIST_GET';
// export const THREEDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS = 'THREEDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS';
// export const THREEDAY_ROOM_MEET_TIME_LIST_GET_ERROR = 'THREEDAY_ROOM_MEET_TIME_LIST_GET_ERROR';

// export const SEVENDAY_ROOM_MEET_TIME_LIST_GET = 'SEVENDAY_ROOM_MEET_TIME_LIST_GET';
// export const SEVENDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS = 'SEVENDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS';
// export const SEVENDAY_ROOM_MEET_TIME_LIST_GET_ERROR = 'SEVENDAY_ROOM_MEET_TIME_LIST_GET_ERROR';

export const OnedayfindRoomReservationCount = createPromiseThunk(ONEDAY_ROOM_RESERVATION_LIST_GET, DashboardApi.findRoomReservationCount);
export const ThreedayfindRoomReservationCount = createPromiseThunk(
    THREEDAY_ROOM_RESERVATION_LIST_GET,
    DashboardApi.findRoomReservationCount
);
export const SevendayfindRoomReservationCount = createPromiseThunk(
    SEVENDAY_ROOM_RESERVATION_LIST_GET,
    DashboardApi.findRoomReservationCount
);
