// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';

import * as DashboardApi from '../../api/DashboardApi';
import { createPromiseThunk } from '../../api/AsyncUtil';

//액션 타입
//?일간 많이 예약된 회의실 개수 조회
export const ONEDAY_ROOM_RESERVATION_LIST_GET = 'ONEDAY_ROOM_RESERVATION_LIST_GET';
export const ONEDAY_ROOM_RESERVATION_LIST_GET_SUCCESS = 'ONEDAY_ROOM_RESERVATION_LIST_GET_SUCCESS';
export const ONEDAY_ROOM_RESERVATION_LIST_GET_ERROR = 'ONEDAY_ROOM_RESERVATION_LIST_GET_ERROR';

export const THREEDAY_ROOM_RESERVATION_LIST_GET = 'THREEDAY_ROOM_RESERVATION_LIST_GET';
export const THREEDAY_ROOM_RESERVATION_LIST_GET_SUCCESS = 'THREEDAY_ROOM_RESERVATION_LIST_GET_SUCCESS';
export const THREEDAY_ROOM_RESERVATION_LIST_GET_ERROR = 'THREEDAY_ROOM_RESERVATION_LIST_GET_ERROR';

export const SEVENDAY_ROOM_RESERVATION_LIST_GET = 'SEVENDAY_ROOM_RESERVATION_LIST_GET';
export const SEVENDAY_ROOM_RESERVATION_LIST_GET_SUCCESS = 'SEVENDAY_ROOM_RESERVATION_LIST_GET_SUCCESS';
export const SEVENDAY_ROOM_RESERVATION_LIST_GET_ERROR = 'SEVENDAY_ROOM_RESERVATION_LIST_GET_ERROR';

//?일간 많이 예약하는 시간대 회의실 조회
export const ONEDAY_ROOM_RESERVATION_TIME_LIST_GET = 'ONEDAY_ROOM_RESERVATION_TIME_LIST_GET';
export const ONEDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS = 'ONEDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS';
export const ONEDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR = 'ONEDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR';

export const THREEDAY_ROOM_RESERVATION_TIME_LIST_GET = 'THREEDAY_ROOM_RESERVATION_TIME_LIST_GET';
export const THREEDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS = 'THREEDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS';
export const THREEDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR = 'THREEDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR';

export const SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET = 'SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET';
export const SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS = 'SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET_SUCCESS';
export const SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR = 'SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET_ERROR';

//?일간 많이 회의가 시작되는 시간대 회의실 조회
export const ONEDAY_ROOM_MEET_TIME_LIST_GET = 'ONEDAY_ROOM_MEET_TIME_LIST_GET';
export const ONEDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS = 'ONEDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS';
export const ONEDAY_ROOM_MEET_TIME_LIST_GET_ERROR = 'ONEDAY_ROOM_MEET_TIME_LIST_GET_ERROR';

export const THREEDAY_ROOM_MEET_TIME_LIST_GET = 'THREEDAY_ROOM_MEET_TIME_LIST_GET';
export const THREEDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS = 'THREEDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS';
export const THREEDAY_ROOM_MEET_TIME_LIST_GET_ERROR = 'THREEDAY_ROOM_MEET_TIME_LIST_GET_ERROR';

export const SEVENDAY_ROOM_MEET_TIME_LIST_GET = 'SEVENDAY_ROOM_MEET_TIME_LIST_GET';
export const SEVENDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS = 'SEVENDAY_ROOM_MEET_TIME_LIST_GET_SUCCESS';
export const SEVENDAY_ROOM_MEET_TIME_LIST_GET_ERROR = 'SEVENDAY_ROOM_MEET_TIME_LIST_GET_ERROR';

// //---------------------------------------------------------------------------------------------------
//?일간 많이 예약된 차량 개수 조회
export const ONEDAY_VEHICLE_RESERVATION_LIST_GET = 'ONEDAY_VEHICLE_RESERVATION_LIST_GET';
export const ONEDAY_VEHICLE_RESERVATION_LIST_GET_SUCCESS = 'ONEDAY_VEHICLE_RESERVATION_LIST_GET_SUCCESS';
export const ONEDAY_VEHICLERESERVATION_LIST_GET_ERROR = 'ONEDAY_VEHICLERESERVATION_LIST_GET_ERROR';

export const THREEDAY_VEHICLE_RESERVATION_LIST_GET = 'THREEDAY_VEHICLE_RESERVATION_LIST_GET';
export const THREEDAY_VEHICLE_RESERVATION_LIST_GET_SUCCESS = 'THREEDAY_VEHICLE_RESERVATION_LIST_GET_SUCCESS';
export const THREEDAY_VEHICLE_RESERVATION_LIST_GET_ERROR = 'THREEDAY_VEHICLE_RESERVATION_LIST_GET_ERROR';

export const SEVENDAY_VEHICLE_RESERVATION_LIST_GET = 'SEVENDAY_VEHICLE_RESERVATION_LIST_GET';
export const SEVENDAY_VEHICLE_RESERVATION_LIST_GET_SUCCESS = 'SEVENDAY_VEHICLE_RESERVATION_LIST_GET_SUCCESS';
export const SEVENDAY_VEHICLE_RESERVATION_LIST_GET_ERROR = 'SEVENDAY_VEHICLE_RESERVATION_LIST_GET_ERROR';

//?일간 많이 예약하는 시간대 차량 조회
export const ONEDAY_VEHICLE_RESERVATION_TIME_LIST_GET = 'ONEDAY_VEHICLE_RESERVATION_TIME_LIST_GET';
export const ONEDAY_VEHICLE_RESERVATION_TIME_LIST_GET_SUCCESS = 'ONEDAY_VEHICLE_RESERVATION_TIME_LIST_GET_SUCCESS';
export const ONEDAY_VEHICLE_RESERVATION_TIME_LIST_GET_ERROR = 'ONEDAY_VEHICLE_RESERVATION_TIME_LIST_GET_ERROR';

export const THREEDAY_VEHICLE_RESERVATION_TIME_LIST_GET = 'THREEDAY_VEHICLE_RESERVATION_TIME_LIST_GET';
export const THREEDAY_VEHICLE_RESERVATION_TIME_LIST_GET_SUCCESS = 'THREEDAY_VEHICLE_RESERVATION_TIME_LIST_GET_SUCCESS';
export const THREEDAY_VEHICLE_RESERVATION_TIME_LIST_GET_ERROR = 'THREEDAY_VEHICLE_RESERVATION_TIME_LIST_GET_ERROR';

export const SEVENDAY_VEHICLE_RESERVATION_TIME_LIST_GET = 'SEVENDAY_VEHICLE_RESERVATION_TIME_LIST_GET';
export const SEVENDAY_VEHICLE_RESERVATION_TIME_LIST_GET_SUCCESS = 'SEVENDAY_VEHICLE_RESERVATION_TIME_LIST_GET_SUCCESS';
export const SEVENDAY_VEHICLE_RESERVATION_TIME_LIST_GET_ERROR = 'SEVENDAY_VEHICLE_RESERVATION_TIME_LIST_GET_ERROR';

//?일간 많이 회의가 시작되는 시간대 차량 조회
export const ONEDAY_VEHICLE_MEET_TIME_LIST_GET = 'ONEDAY_VEHICLE_MEET_TIME_LIST_GET';
export const ONEDAY_VEHICLE_MEET_TIME_LIST_GET_SUCCESS = 'ONEDAY_VEHICLE_MEET_TIME_LIST_GET_SUCCESS';
export const ONEDAY_VEHICLE_MEET_TIME_LIST_GET_ERROR = 'ONEDAY_VEHICLE_MEET_TIME_LIST_GET_ERROR';

export const THREEDAY_VEHICLE_MEET_TIME_LIST_GET = 'THREEDAY_VEHICLE_MEET_TIME_LIST_GET';
export const THREEDAY_VEHICLE_MEET_TIME_LIST_GET_SUCCESS = 'THREEDAY_VEHICLE_MEET_TIME_LIST_GET_SUCCESS';
export const THREEDAY_VEHICLE_MEET_TIME_LIST_GET_ERROR = 'THREEDAY_VEHICLE_MEET_TIME_LIST_GET_ERROR';

export const SEVENDAY_VEHICLE_MEET_TIME_LIST_GET = 'SEVENDAY_VEHICLE_MEET_TIME_LIST_GET';
export const SEVENDAY_VEHICLE_MEET_TIME_LIST_GET_SUCCESS = 'SEVENDAY_VEHICLE_MEET_TIME_LIST_GET_SUCCESS';
export const SEVENDAY_VEHICLE_MEET_TIME_LIST_GET_ERROR = 'SEVENDAY_VEHICLE_MEET_TIME_LIST_GET_ERROR';

// //---------------------------------------------------------------------------------------------------

// 즐겨찾기 TOP3 회의실
export const BOOKMARK_ROOM_TOP_GET = 'BOOKMARK_ROOM_TOP_GET';
export const BOOKMARK_ROOM_TOP_GET_SUCCESS = 'BOOKMARK_ROOM_TOP_GET_SUCCESS';
export const BOOKMARK_ROOM_TOP_GET_ERROR = 'BOOKMARK_ROOM_TOP_GET_ERROR';
// 즐겨찾기 TOP3 차량
export const BOOKMARK_VEHICLE_TOP_GET = 'BOOKMARK_VEHICLE_TOP_GET';
export const BOOKMARK_VEHICLE_TOP_GET_SUCCESS = 'BOOKMARK_VEHICLE_TOP_GET_SUCCESS';
export const BOOKMARK_VEHICLE_TOP_GET_ERROR = 'BOOKMARK_VEHICLE_TOP_GET_ERROR';

//최근 예약된 회의실
export const RECENT_ROOM_RESERVATION_GET = 'RECENT_ROOM_RESERVATION_GET';
export const RECENT_ROOM_RESERVATION_GET_SUCCESS = 'RECENT_ROOM_RESERVATION_GET_SUCCESS';
export const RECENT_ROOM_RESERVATION_GET_ERROR = 'RECENT_ROOM_RESERVATION_GET_ERROR';
//최근 예약된 차량
export const RECENT_VEHICLE_RESERVATION_GET = 'RECENT_VEHICLE_RESERVATION_GET';
export const RECENT_VEHICLE_RESERVATION_GET_SUCCESS = 'RECENT_VEHICLE_RESERVATION_GET_SUCCESS';
export const RECENT_VEHICLE_RESERVATION_GET_ERROR = 'RECENT_VEHICLE_RESERVATION_GET_ERROR';
// //---------------------------------------------------------------------------------------------------
export const OnedayfindRoomReservationCount = createPromiseThunk(ONEDAY_ROOM_RESERVATION_LIST_GET, DashboardApi.findRoomReservationCount);
export const ThreedayfindRoomReservationCount = createPromiseThunk(
    THREEDAY_ROOM_RESERVATION_LIST_GET,
    DashboardApi.findRoomReservationCount
);
export const SevendayfindRoomReservationCount = createPromiseThunk(
    SEVENDAY_ROOM_RESERVATION_LIST_GET,
    DashboardApi.findRoomReservationCount
);

export const OnedayfindRoomReservationTime = createPromiseThunk(
    ONEDAY_ROOM_RESERVATION_TIME_LIST_GET,
    DashboardApi.findRoomReservationTime
);
export const ThreedayfindRoomReservationTime = createPromiseThunk(
    THREEDAY_ROOM_RESERVATION_TIME_LIST_GET,
    DashboardApi.findRoomReservationTime
);
export const SevendayfindRoomReservationTime = createPromiseThunk(
    SEVENDAY_ROOM_RESERVATION_TIME_LIST_GET,
    DashboardApi.findRoomReservationTime
);

export const OnedayfindRoomMeetTime = createPromiseThunk(ONEDAY_ROOM_MEET_TIME_LIST_GET, DashboardApi.findRoomMeetTime);
export const ThreedayfindRoomMeetTime = createPromiseThunk(THREEDAY_ROOM_MEET_TIME_LIST_GET, DashboardApi.findRoomMeetTime);
export const SevendayfindRoomMeetTime = createPromiseThunk(SEVENDAY_ROOM_MEET_TIME_LIST_GET, DashboardApi.findRoomMeetTime);

export const OnedayfindVehicleReservationCount = createPromiseThunk(
    ONEDAY_VEHICLE_RESERVATION_LIST_GET,
    DashboardApi.findVehicleReservationCount
);
export const ThreedayfindVehicleReservationCount = createPromiseThunk(
    THREEDAY_VEHICLE_RESERVATION_LIST_GET,
    DashboardApi.findVehicleReservationCount
);
export const SevendayfindVehicleReservationCount = createPromiseThunk(
    SEVENDAY_VEHICLE_RESERVATION_LIST_GET,
    DashboardApi.findVehicleReservationCount
);

export const OnedayfindVehicleReservationTime = createPromiseThunk(
    ONEDAY_VEHICLE_RESERVATION_TIME_LIST_GET,
    DashboardApi.findVehicleReservationTime
);
export const ThreedayfindVehicleReservationTime = createPromiseThunk(
    THREEDAY_VEHICLE_RESERVATION_TIME_LIST_GET,
    DashboardApi.findVehicleReservationTime
);
export const SevendayfindVehicleReservationTime = createPromiseThunk(
    SEVENDAY_VEHICLE_RESERVATION_TIME_LIST_GET,
    DashboardApi.findVehicleReservationTime
);

export const OnedayfindVehicleStartTime = createPromiseThunk(ONEDAY_VEHICLE_MEET_TIME_LIST_GET, DashboardApi.findVehicleStartTime);
export const ThreedayfindVehicleStartTime = createPromiseThunk(THREEDAY_VEHICLE_MEET_TIME_LIST_GET, DashboardApi.findVehicleStartTime);
export const SevendayfindVehicleStartTime = createPromiseThunk(SEVENDAY_VEHICLE_MEET_TIME_LIST_GET, DashboardApi.findVehicleStartTime);
// //---------------------------------------------------------------------------------------------------

export const RoomBookmarkTop = createPromiseThunk(BOOKMARK_ROOM_TOP_GET, DashboardApi.findRoomBookMarkTop);
export const VehicleBookmarkTop = createPromiseThunk(BOOKMARK_VEHICLE_TOP_GET, DashboardApi.findVehicleBookMarkTop);

export const recentRoomRervation = createPromiseThunk(RECENT_ROOM_RESERVATION_GET, DashboardApi.findRecentReservationRoom);
export const recentVehicleRervation = createPromiseThunk(RECENT_VEHICLE_RESERVATION_GET, DashboardApi.findRecentReservationVehicle);
